# Generated by Django 5.0.6 on 2024-07-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='slider_text',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus quis eum', null=True),
        ),
    ]
