# Generated by Django 5.0.7 on 2024-07-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='Nombre y apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('consulttype', models.CharField(max_length=60, verbose_name='Tipo de consulta')),
                ('comments', models.TextField(verbose_name='Mensaje')),
                ('bulletin', models.BooleanField(verbose_name='Suscripto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
    ]
